# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrecon < Formula
  desc "AWSrecon is a tool for reconnaissance AWS cloud environments"
  homepage "https://github.com/hupe1980/awsrecon"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.18/awsrecon_Darwin_x86_64.tar.gz"
      sha256 "470ad659cf1e336fe18b694cc64a2ea8e5c70df6b4cabc99096d8adfbffa9a54"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.18/awsrecon_Darwin_arm64.tar.gz"
      sha256 "bf14171fe616bc83b4ec4f7ecb54d2075516ec9416cc0efe4b5d724c562aac5d"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.18/awsrecon_Linux_armv6.tar.gz"
      sha256 "6536d33295bc064878ccc532b765cb7bf270bfea28d1937390d6224325538469"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.18/awsrecon_Linux_arm64.tar.gz"
      sha256 "e19ab1aeedad6c08042ff94d410c064d723502b2215160fcf643b4190d0f3d7b"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.18/awsrecon_Linux_x86_64.tar.gz"
      sha256 "e320364d4d06e754e72343df8be12ba9908d86b5bfd17f756ca205cfa512414d"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
  end

  test do
    system "#{bin}/awsrecon -v"
  end
end
