# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrecon < Formula
  desc "AWSrecon is a tool for reconnaissance AWS cloud environments"
  homepage "https://github.com/hupe1980/awsrecon"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.14/awsrecon_Darwin_arm64.tar.gz"
      sha256 "052b2743177fe6a689ccef97f90887a7e1cd6c8c17b41fdbdfb9cdb5091192df"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.14/awsrecon_Darwin_x86_64.tar.gz"
      sha256 "a2b17ad588dbe321774acba7fdd73e532159a8d1007b7c429e91a0db4710465d"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.14/awsrecon_Linux_x86_64.tar.gz"
      sha256 "a0227105b180f2b4f6740443a5b5713d0e4d485769e506ba93642da65e8bce34"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.14/awsrecon_Linux_armv6.tar.gz"
      sha256 "90d734d8d4510edc42e61aede257588ffcc0b88988a36d931fd534b2c66f2d51"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/awsrecon/releases/download/v0.0.14/awsrecon_Linux_arm64.tar.gz"
      sha256 "a78e66151fae16c4d3e779a6c293bb1df75996914f0f041c4b5cce0b7c055ce3"

      def install
        bin.install "awsrecon"
        bash_completion.install "completions/awsrecon.bash" => "awsrecon"
        zsh_completion.install "completions/awsrecon.zsh" => "_awsrecon"
        fish_completion.install "completions/awsrecon.fish"
      end
    end
  end

  test do
    system "#{bin}/awsrecon -v"
  end
end
